// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8KiVS7IQmWLPMnOLA16SUF6se_LazA8',
    appId: '1:383279579774:web:ec155febad05a379dc8e2f',
    messagingSenderId: '383279579774',
    projectId: 'musicos-universal',
    authDomain: 'musicos-universal.firebaseapp.com',
    storageBucket: 'musicos-universal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCoec6fqSo3551O8zm75Xn0wLo1ZkQDio',
    appId: '1:383279579774:android:650e6fc5f0aa4b04dc8e2f',
    messagingSenderId: '383279579774',
    projectId: 'musicos-universal',
    storageBucket: 'musicos-universal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbou_u1YFXv09hliJUbHSnSi4vrFy5QH4',
    appId: '1:383279579774:ios:35aeba81e5399b31dc8e2f',
    messagingSenderId: '383279579774',
    projectId: 'musicos-universal',
    storageBucket: 'musicos-universal.firebasestorage.app',
    iosBundleId: 'com.example.musicosUniversal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbou_u1YFXv09hliJUbHSnSi4vrFy5QH4',
    appId: '1:383279579774:ios:35aeba81e5399b31dc8e2f',
    messagingSenderId: '383279579774',
    projectId: 'musicos-universal',
    storageBucket: 'musicos-universal.firebasestorage.app',
    iosBundleId: 'com.example.musicosUniversal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8KiVS7IQmWLPMnOLA16SUF6se_LazA8',
    appId: '1:383279579774:web:3d82c9182c03bdfddc8e2f',
    messagingSenderId: '383279579774',
    projectId: 'musicos-universal',
    authDomain: 'musicos-universal.firebaseapp.com',
    storageBucket: 'musicos-universal.firebasestorage.app',
  );
}
